import { NextResponse } from 'next/server'

const SKILLS = [
  {
    id: 'storage-analyzer',
    name: '存储分析',
    englishName: 'Storage Analyzer',
    icon: '💾',
    oneLiner: '一句话扫描整机磁盘，三色分级给清理决策，网页上一键移废纸篓',
    tags: ['macOS', 'Windows', '磁盘', '清理'],
    description: '随口跟 Agent 说一句"帮我看看存储"或"C 盘满了"，它会扫一遍整机磁盘，在浏览器里打开一份交互式 HTML 报告：磁盘总览、占用 Top 5、清理优先级、🟢🟡🔴 三色分级清单。命令一键复制，也可以直接点按钮移到废纸篓 / 删除（每次都有二次确认弹窗）。',
    features: [
      '只读扫描，绝不擅自动手',
      '🟢🟡🔴 三色分级清理决策',
      '交互式 HTML 报告，一键删除',
      'macOS 完整实测，Windows 代码就绪',
    ],
    triggerWords: ['帮我看看存储', 'C盘满了', '清理磁盘', '磁盘清理', 'storage analysis'],
    platform: 'macOS / Windows',
    repoUrl: 'https://github.com/KKKKhazix/khazix-skills/tree/main/storage-analyzer',
  },
  {
    id: 'aihot',
    name: 'AI HOT 资讯查询',
    englishName: 'AI HOT',
    icon: '🔥',
    oneLiner: '让 Agent 用一句话拿到每天的 AI HOT 日报和全部 AI 动态，无需 API Key',
    tags: ['AI', '资讯', '日报', '搜索'],
    description: '让支持 SKILL.md 的 Agent 用最自然的中文一句话拿到 aihot.virxact.com 每天的 AI HOT 日报和全部 AI 动态。无需 API Key、无需配 MCP server。支持按分类、时间窗口、关键词搜索 AI 动态。',
    features: [
      '拉今日 / 指定日期的 AI HOT 日报',
      '按分类拉条目（模型/产品/行业/论文/技巧）',
      '关键词 / 公司 / 主题搜索',
      '跨平台：Claude Code / Codex / Cursor / Gemini CLI',
    ],
    triggerWords: ['今天 AI 圈有什么新东西', 'AI 日报', '最近 AI 论文', 'AI hot today'],
    platform: '全平台',
    repoUrl: 'https://github.com/KKKKhazix/khazix-skills/tree/main/aihot',
  },
  {
    id: 'neat-freak',
    name: '洁癖',
    englishName: 'Neat Freak',
    icon: '🧹',
    oneLiner: '干完活跑一下 /neat，自动把改的东西跟项目文档、CLAUDE.md、Agent 记忆全部对齐',
    tags: ['文档', '同步', '记忆', 'CLAUDE.md'],
    description: '每次你在 Agent 里干完一件事，跑一下 /neat，它会把你这次会话改的东西，跟项目里的文档、CLAUDE.md / AGENTS.md、Agent 记忆全部对齐一遍，最后给你一份变更摘要。不是模型变笨，是文档和记忆脑腐了。neat-freak 就是清这个的。',
    features: [
      '三层知识同步：CLAUDE.md + docs + Agent 记忆',
      '防膨胀：自动精简过大的配置文件',
      '变更影响矩阵：自动识别跨项目影响',
      '自检清单确保零遗漏',
    ],
    triggerWords: ['/neat', '整理一下', '同步一下', 'sync up'],
    platform: 'Claude Code / Codex / OpenCode / OpenClaw',
    repoUrl: 'https://github.com/KKKKhazix/khazix-skills/tree/main/neat-freak',
  },
  {
    id: 'hv-analysis',
    name: '横纵分析法',
    englishName: 'HV Analysis',
    icon: '🔭',
    oneLiner: '想搞懂一个产品/公司/概念是怎么回事，丢给它，给你一份万字 PDF 研究报告',
    tags: ['研究', '分析', 'PDF', '竞品'],
    description: '想搞懂一个产品 / 公司 / 概念 / 人物到底是怎么回事，丢给它就行。它会同时跑两条线：纵向把研究对象从诞生讲到当下，像讲故事一样把演变讲完整；横向把同期所有主要竞品摆出来逐一对比。最后两条线一交叉，能看出一些只看现状或只看历史看不出来的东西。最终给你一份排版精美的 PDF 研究报告，10,000–30,000 字。',
    features: [
      '纵向追时间深度，横向追同期广度',
      '10,000–30,000 字 PDF 研究报告',
      '联网信息收集 + 并行搜索策略',
      '四层质检体系确保报告质量',
    ],
    triggerWords: ['横纵分析', '研究一下', '深度研究', '竞品分析', '做个研究'],
    platform: '全平台',
    repoUrl: 'https://github.com/KKKKhazix/khazix-skills/tree/main/hv-analysis',
  },
  {
    id: 'khazix-writer',
    name: '卡兹克写作',
    englishName: 'Khazix Writer',
    icon: '✍️',
    oneLiner: '装上之后，Agent 用我的口吻和节奏写公众号长文',
    tags: ['写作', '公众号', '风格', '长文'],
    description: '我自己写公众号的那套写作 skill。装上之后，Agent 写出来的东西就是我的口吻、我的节奏、我的禁忌词全在里面。它会拒绝写「赋能、抓手、闭环」、拒绝「首先...其次」、拒绝「在当今 AI 快速发展的时代」。完整的写作风格规则 + 四层自检体系 + 一套风格示例库。',
    features: [
      '完整的写作风格规则（节奏、叙事、判断、修辞）',
      '四层自检体系（结构、节奏、内容、文字）',
      '风格示例库（可以让 AI 直接对照）',
      '禁用词 / 禁用标点自动扫描',
    ],
    triggerWords: ['写文章', '写稿子', '帮我写', '续写', '公众号文章'],
    platform: '全平台',
    repoUrl: 'https://github.com/KKKKhazix/khazix-skills/tree/main/khazix-writer',
  },
  {
    id: 'changelog-generator',
    name: '变更日志生成',
    englishName: 'Changelog Generator',
    icon: '📋',
    oneLiner: '从 git 历史自动生成用户友好的 Changelog，支持 Conventional Commits',
    tags: ['Git', 'Changelog', '版本管理', '自动化'],
    description: '从 git 历史自动生成用户友好的 Changelog，支持 Conventional Commits 解析、版本分类、Breaking Changes 高亮。脚本自动完成提交历史获取、类型解析、分类汇总，Agent 再审查补充上下文和合并同类项。',
    features: [
      'Conventional Commits 自动解析',
      'Breaking Changes 高亮标记',
      '按类型分组（feat/fix/docs/refactor 等）',
      '零第三方依赖，Python 3 标准库',
    ],
    triggerWords: ['生成变更日志', 'changelog', '版本更新记录', 'release notes'],
    platform: '全平台',
    repoUrl: 'https://github.com/KKKKhazix/khazix-skills/tree/main/changelog-generator',
  },
  {
    id: 'security-scanner',
    name: '安全扫描',
    englishName: 'Security Scanner',
    icon: '🔒',
    oneLiner: '一句话对 Web 应用做安全体检，检测信息泄露/不安全头/混合内容/过期 SSL',
    tags: ['安全', '扫描', '漏洞', 'Web'],
    description: '对 Web 应用进行基础安全扫描，检测常见漏洞（信息泄露、不安全头、混合内容、过期 SSL），生成安全评估报告。按严重级别分类（Critical/Warning/Info），给出可执行的修复建议。',
    features: [
      'SSL/TLS 证书检测',
      '安全头检测（CSP/HSTS/X-Frame-Options 等）',
      '信息泄露检测',
      '混合内容 & Cookie 安全检查',
    ],
    triggerWords: ['安全扫描', '漏洞扫描', 'security scan', '安全检查'],
    platform: '全平台',
    repoUrl: 'https://github.com/KKKKhazix/khazix-skills/tree/main/security-scanner',
  },
  {
    id: 'webapp-testing',
    name: 'Web 应用测试',
    englishName: 'Webapp Testing',
    icon: '🧪',
    oneLiner: '一句话启动 Web 应用测试，自动检测可访问性/链接/性能/安全，生成报告',
    tags: ['测试', 'Web', '性能', '自动化'],
    description: '一句话启动 Web 应用全面体检，自动检测页面可访问性、链接完整性、性能指标、安全头配置，生成 HTML 测试报告。覆盖 HTTP 状态检查、SSL 证书验证、安全头检测、链接完整性爬取、页面大小记录。',
    features: [
      'HTTP 状态 & 响应时间检测',
      'SSL 证书有效性验证',
      '链接完整性自动爬取',
      '安全头配置检测',
    ],
    triggerWords: ['测试网站', 'web测试', '网站体检', 'webapp test'],
    platform: '全平台',
    repoUrl: 'https://github.com/KKKKhazix/khazix-skills/tree/main/webapp-testing',
  },
]

export async function GET() {
  return NextResponse.json({ skills: SKILLS })
}
